### ISSUE TITLE
How to get output

### ISSUE THREAD

**Issue by danieldunderfelt** [tracker1/node-ms-sqlcmd#5]
I was going to use this library, but I'm unsure how to get the output of the command. It just returns undefined. Then I noticed that it actually never returns the output:

https://github.com/tracker1/node-ms-sqlcmd/blob/ae2237e67754b410fe21e527b4e94e8d4f90b2ad/src/execute-request/index.js#L15

What gives? Is it supposed to just do something and never return anything? The example in the readme specifically assigns the output of `sqlcmd` to a variable called `output`.

**Comment by cwood-panopto** [comment]
I am trying to do the same.

**Comment by tracker1** [comment]
you can set echo:true in the options if you want to see terminal output.
